### PR TITLE
feat: add a responsive event detail hero page

### LINKED ISSUE #9: Implement Event Detail Hero Section
Create and implement the hero section for individual event details pages. The hero section serves as the focal point of each event detail page, providing a visually appealing introduction to the specific event and encouraging attendees' interest.

image

### PR DESCRIPTION
**Pull request by lokesh-wagh**
fixes #9

### CODE REVIEW

**Comment by lokesh-wagh** [comment]
image
build has been successful locally

don't know why it is causing issue's

**Comment by rohin079** [comment]
@lokesh-wagh  Kindly loot at the build preview logs to find out why the build is failing, correct it and then try to raise another commit until all checks are passed

**Comment by lokesh-wagh** [comment]
hey the build issue's are resolved can you merge it now

**Comment by rohin079** [comment]
@lokesh-wagh the css of the homepage has been changed due to which its UI is looking different :

image

kindly update that to make it look like this again:

image

**Comment by lokesh-wagh** [comment]
hey !!

i have fixed the UI issue

**Comment by rohin079** [comment]
@lokesh-wagh The dark theme button is still left, other than that, great work! Commit that and i'll close the issue as completed

**Comment by lokesh-wagh** [comment]
Can you elaborate what i am supposed to do with the dark themed button

**Comment by rohin079** [comment]
> Can you elaborate what i am supposed to do with the dark themed button

The alighment of the dark theme button has been changed ( refer to the ss) and its animation has stopped working w your commit, fix that to how it were before you added your changes: https://upes-gdsc.netlify.app/ Look at the dark theme button on this page at top right

**Comment by rohin079** [comment]
@lokesh-wagh Any updates?

**Comment by lokesh-wagh** [comment]
Hey!!

Can i get some more time to fix this minor issue
Actually i have a techfest to compete in at my college

**Comment by rohin079** [comment]
@lokesh-wagh Sure, no issues :)

**Comment by rohin079** [comment]
@lokesh-wagh Any updates?

**Comment by lokesh-wagh** [comment]
Hey !!
I am closing this PR since i need to prepare for ICPC
sry

**Pull request closed without merging**
