### PR TITLE
added a component

### PR DESCRIPTION
**Pull request by lokesh-wagh**
Created a EventDetailHeroComponent that can render the eventDetailHero section

Props need to be passed to the component

### CODE REVIEW

**Comment by rohin079** [comment]
Hi @lokesh-wagh I took a look at your PR, great work! However there are some changes that needs to be implemented before i can close this PR as completed:

1. Try Scaling down the components size as they look very magnified at the moment
2. Replace the current fonts from the used fonts from Figma file ( attached in README file)
3. Remove the unnecessary text from the hero section 
4. Try adding media query to make the section responsive for mobile devices as well

**Comment by lokesh-wagh** [comment]
Ok i will make the changes

**Comment by lokesh-wagh** [comment]
Hey!!

How does the responsive design need to be 
any figma for that or same as the desktop figma with same size

**Comment by akshit-g** [comment]
> Hey!!
> 
> How does the responsive design need to be 
> any figma for that or same as the desktop figma with same size

We're using the same Figma file, but you just need to adapt it for mobile devices.

**Pull request closed without merging**
