### PR TITLE
feat: home hero section [#2]

### PR DESCRIPTION
**Pull request by ansisme**

### CODE REVIEW

**Comment by rohin079** [comment]
@ansisme The home page hero section isn't visible in the hompage:

image

Also the UI for dark theme button at top right has been changed, kindly revert that to how it were.

**Comment by ansisme** [comment]
Okay there 's an issue in rendering hero section, will correct it.
I did not change any styling of the navbar components, neither the dark theme button.

**Comment by ansisme** [comment]
done

**Comment by rohin079** [comment]
@ansisme The hero section looks flawless, great work on that, however on checking the navbar i figured out that the dark theme button has been changed from your commit :

image

Before your commit this is how the button used to be:

image

This change may have been unintentional, please review your changed files again to see the exact issue. Other than that great work, i'll merge your PR as completed once the button have been fixed:)

**Comment by ansisme** [comment]
sure, will do that!

**Comment by ansisme** [comment]
done

**Pull request merged**
